language: python
python:
 - "3.6"
install:
 - "pip install --process-dependency-links -e .[test]"
script:
 - "flake8 ."
 - "./build.sh"
notifications:
  email: false
  irc:
    channels:
     - "chat.freenode.net#concertdaw"
    on_success: change
    on_failure: change
    template:
     - "%{repository_name}/%{branch} %{result}: %{build_url}"
